apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: weatherforecast-steeltoe
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: weatherforecast-steeltoe
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: steeltoe-weatherforecast
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/jrobinsonvm/steeltoe-weatherforecast
      ref:
        branch: main
